exclude: '^$|venv'
fail_fast: false
repos:
  - repo: git@github.com:pre-commit/pre-commit-hooks
    rev: v2.1.0
    hooks:
      - id: check-added-large-files
      - id: flake8
  - repo: https://github.com/ambv/black
    rev: stable
    hooks:
      - id: black
        language_version: python3.8
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: master
    hooks:
      - id: mypy
        args: ['--check-untyped-defs']
  - repo: git@github.com:Justice4Joffrey/hooks.git
    rev: master
    hooks:
      - id: autoflake
