exclude: '^$|venv'
fail_fast: false
repos:
  - repo: local
    hooks:
      - id: isort
        name: isort
        entry: isort
        language: python
        types: [python]
  - repo: local
    hooks:
      - id: autoflake
        name: autoflake
        entry: autoflake
        args: ["--remove-all-unused-imports", "--recursive", "--remove-unused-variables", "--in-place"]
        language: python
        types: [python]
  - repo: git@github.com:pre-commit/pre-commit-hooks
    rev: v2.1.0
    hooks:
      - id: check-added-large-files
      - id: flake8
  - repo: https://github.com/ambv/black
    rev: stable
    hooks:
      - id: black
        language_version: python3.8
  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: mypy
        language: python
        types: [python]
